name: pine_bricks_helper
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  checked_yaml: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
